using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace AIGoalCoach.Core.DTOs
{
    public class GoalResponse
    {
        [Required]
        [StringLength(300, MinimumLength = 10)]
        [Display(
            Name = "Refined Goal",
            Description = "The SMART version of the user's original goal generated by the AI."
        )]
        [JsonProperty("refined_goal")]
        public string RefinedGoal { get; set; } = string.Empty;


        [Required]
        [MinLength(3)]
        [MaxLength(5)]
        [Display(
            Name = "Key Results",
            Description = "A list of 3 to 5 measurable steps required to achieve the refined goal."
        )]
        [JsonProperty("key_results")]
        public List<string> KeyResults { get; set; } = new();


        [Required]
        [Range(1, 10)]
        [Display(
            Name = "Confidence Score",
            Description = "AI confidence score from 1 to 10 indicating how likely the input is a real goal."
        )]
        [JsonProperty("confidence_score")]
        public int ConfidenceScore { get; set; }
    }
}
